//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autodata", Namespace="http://schemas.datacontract.org/2004/07/AutokauppaWCF")]
    [System.SerializableAttribute()]
    public partial class Autodata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMalliIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMerkkiIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HintaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerkkiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MittarilukemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Moottorin_tilavuusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolttoaineIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Polttoaineen_nimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rekisteri_paivamaaraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Varin_nimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VaritIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMalliID {
            get {
                return this.AutonMalliIDField;
            }
            set {
                if ((this.AutonMalliIDField.Equals(value) != true)) {
                    this.AutonMalliIDField = value;
                    this.RaisePropertyChanged("AutonMalliID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMerkkiID {
            get {
                return this.AutonMerkkiIDField;
            }
            set {
                if ((this.AutonMerkkiIDField.Equals(value) != true)) {
                    this.AutonMerkkiIDField = value;
                    this.RaisePropertyChanged("AutonMerkkiID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hinta {
            get {
                return this.HintaField;
            }
            set {
                if ((this.HintaField.Equals(value) != true)) {
                    this.HintaField = value;
                    this.RaisePropertyChanged("Hinta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Merkki {
            get {
                return this.MerkkiField;
            }
            set {
                if ((object.ReferenceEquals(this.MerkkiField, value) != true)) {
                    this.MerkkiField = value;
                    this.RaisePropertyChanged("Merkki");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mittarilukema {
            get {
                return this.MittarilukemaField;
            }
            set {
                if ((this.MittarilukemaField.Equals(value) != true)) {
                    this.MittarilukemaField = value;
                    this.RaisePropertyChanged("Mittarilukema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Moottorin_tilavuus {
            get {
                return this.Moottorin_tilavuusField;
            }
            set {
                if ((this.Moottorin_tilavuusField.Equals(value) != true)) {
                    this.Moottorin_tilavuusField = value;
                    this.RaisePropertyChanged("Moottorin_tilavuus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolttoaineID {
            get {
                return this.PolttoaineIDField;
            }
            set {
                if ((this.PolttoaineIDField.Equals(value) != true)) {
                    this.PolttoaineIDField = value;
                    this.RaisePropertyChanged("PolttoaineID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polttoaineen_nimi {
            get {
                return this.Polttoaineen_nimiField;
            }
            set {
                if ((object.ReferenceEquals(this.Polttoaineen_nimiField, value) != true)) {
                    this.Polttoaineen_nimiField = value;
                    this.RaisePropertyChanged("Polttoaineen_nimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rekisteri_paivamaara {
            get {
                return this.Rekisteri_paivamaaraField;
            }
            set {
                if ((this.Rekisteri_paivamaaraField.Equals(value) != true)) {
                    this.Rekisteri_paivamaaraField = value;
                    this.RaisePropertyChanged("Rekisteri_paivamaara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varin_nimi {
            get {
                return this.Varin_nimiField;
            }
            set {
                if ((object.ReferenceEquals(this.Varin_nimiField, value) != true)) {
                    this.Varin_nimiField = value;
                    this.RaisePropertyChanged("Varin_nimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VaritID {
            get {
                return this.VaritIDField;
            }
            set {
                if ((this.VaritIDField.Equals(value) != true)) {
                    this.VaritIDField = value;
                    this.RaisePropertyChanged("VaritID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUserDetails", ReplyAction="http://tempuri.org/IService1/InsertUserDetailsResponse")]
        string InsertUserDetails(Auto.ServiceReference1.Autodata userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUserDetails", ReplyAction="http://tempuri.org/IService1/InsertUserDetailsResponse")]
        System.Threading.Tasks.Task<string> InsertUserDetailsAsync(Auto.ServiceReference1.Autodata userinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAutodata", ReplyAction="http://tempuri.org/IService1/SelectAutodataResponse")]
        System.Data.DataSet SelectAutodata();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAutodata", ReplyAction="http://tempuri.org/IService1/SelectAutodataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectAutodataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Auto.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Auto.ServiceReference1.IService1>, Auto.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertUserDetails(Auto.ServiceReference1.Autodata userinfo) {
            return base.Channel.InsertUserDetails(userinfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertUserDetailsAsync(Auto.ServiceReference1.Autodata userinfo) {
            return base.Channel.InsertUserDetailsAsync(userinfo);
        }
        
        public System.Data.DataSet SelectAutodata() {
            return base.Channel.SelectAutodata();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectAutodataAsync() {
            return base.Channel.SelectAutodataAsync();
        }
    }
}
